import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export default function TermsPage() {
  return (
    <>
      <Navbar />

      <main className="flex-1 max-w-4xl mx-auto w-full py-12 px-6">
        <section className="text-center mb-8">
          <h1 className="text-4xl font-black font-display tracking-tight text-retro-navy dark:text-cream mb-2">
            Terms of Service
          </h1>
          <p className="font-medium opacity-85">Last updated: July 2026</p>
        </section>

        <section className="neo-card p-8 bg-white dark:bg-retro-navy prose dark:prose-invert font-medium space-y-6">
          <h2 className="text-2xl font-black font-display border-b-3 border-retro-navy dark:border-cream pb-2">
            1. Acceptance of Terms
          </h2>
          <p className="leading-relaxed">
            By accessing and using GameWheelClub, you agree to comply with and be bound by these terms. If you do not agree to these terms, please do not use our services.
          </p>

          <h2 className="text-2xl font-black font-display border-b-3 border-retro-navy dark:border-cream pb-2 pt-4">
            2. Permitted Use
          </h2>
          <p className="leading-relaxed">
            Our tools are designed for personal, classroom, and non-commercial decision making. You are free to customize option lists for your utility, but you must not exploit, scrape, or perform malicious attacks against the platform.
          </p>

          <h2 className="text-2xl font-black font-display border-b-3 border-retro-navy dark:border-cream pb-2 pt-4">
            3. Disclaimer of Warranties
          </h2>
          <p className="leading-relaxed">
            Our decision wheel generator is provided &quot;as is&quot; without any warranty. Results generated by the wheel are randomized and do not constitute professional advice or legally binding decisions. Use of the wheel is at your own risk.
          </p>
        </section>
      </main>

      <Footer />
    </>
  );
}
